services:
  - type: web
    name: heart-mate
    env: node
    plan: free
    buildCommand: |
      cd backend && npm i && cd ../frontend && npm i && npm run build
    startCommand: |
      cd backend && NODE_ENV=production PORT=$PORT CLIENT_ORIGIN=$RENDER_EXTERNAL_URL node server.js
    autoDeploy: true
    rootDir: .
    region: oregon
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_PATH
        value: /var/data/tricog_health.db
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DOCTOR_TELEGRAM_CHAT_ID
        sync: false
      - key: GOOGLE_CALENDAR_CREDENTIALS
        sync: false
      - key: DOCTOR_EMAIL
        sync: false
    disks:
      - name: data
        mountPath: /var/data

